'use strict';
// 저장된 관계를 배치하고 상태 변경은 기존 노드에 반영한다.
window.ResearchFlowMap=(()=>{
 const modes={all:'전체 연구',current:'현재 작업',recovery:'오류·복구',verification:'검증'};
 const states={QUEUED:'대기',RUNNING:'실행 중',VERIFYING:'검증 중',REPAIRING:'복구 중',COMPLETED:'완료',NEEDS_REVIEW:'검토 필요',FAILED:'실패',BLOCKED:'중단',PAUSED:'일시정지',SUPERSEDED:'이전 수정본',INVALIDATED:'무효화',VALIDATION_INCOMPLETE:'재검증 미완료',UNKNOWN:'정보 없음',DRAFT:'준비',AVAILABLE:'보고서 있음'};
 const icons={QUEUED:'◷',RUNNING:'▶',VERIFYING:'◇',REPAIRING:'↻',COMPLETED:'✓',NEEDS_REVIEW:'!',FAILED:'×',BLOCKED:'■',PAUSED:'Ⅱ',SUPERSEDED:'↗',INVALIDATED:'×',VALIDATION_INCOMPLETE:'!'};
 const relations={depends_on:'의존',produces:'생성',uses:'사용',supports:'뒷받침',contradicts:'반증',qualifies:'제한',verifies:'검증',repairs:'복구',supersedes:'교체',invalidates:'무효화'};
 let rid=null,view='current',offset=0,selected=null,busy=false,data=null,positions=new Map(),expanded=new Set(),layoutRuns=0,updates=0,generation=0;
 let options={};
 function mount(host,research,configuration={}){generation++;busy=false;options=configuration;rid=research;view=options.view||'all';offset=0;selected=null;positions=new Map();expanded=new Set();data=null;layoutRuns=0;updates=0;
  host.innerHTML=`<section id="research-flow" aria-label="연구 흐름"><div class="flow-toolbar" role="group" aria-label="흐름 범위">${Object.entries(modes).map(([k,v])=>`<button data-flow-view="${k}" aria-pressed="${k===view}">${v}</button>`).join('')}<button id="flow-refresh">새로고침</button></div><div id="flow-status" role="status" aria-live="polite"></div><div class="flow-viewport" tabindex="0" aria-label="연구 흐름 · 논리적 진행 순서"><div class="flow-diagram"><svg class="flow-edges" aria-hidden="true"></svg><div class="flow-lanes"></div><div class="flow-nodes"></div></div></div><div class="flow-footer"><span id="flow-count"></span><div><button id="flow-prev">이전</button><button id="flow-next">다음</button></div></div><div class="flow-legend">${Object.entries(relations).map(([k,v])=>`<span data-relation="${k}">${v}</span>`).join('')}</div></section>`;
  host.querySelectorAll('[data-flow-view]').forEach(b=>b.onclick=()=>{generation++;busy=false;view=b.dataset.flowView;offset=0;selected=null;positions=new Map();host.querySelectorAll('[data-flow-view]').forEach(x=>x.setAttribute('aria-pressed',x===b));refresh();});
  $('#flow-refresh').onclick=()=>refresh();$('#flow-prev').onclick=()=>{generation++;busy=false;offset=Math.max(0,offset-data.limit);refresh();};$('#flow-next').onclick=()=>{generation++;busy=false;offset=data.next_offset;refresh();};
  return refresh();
 }
 function shown(){return data.nodes.filter(n=>n.kind!=='agent_run'||expanded.has(n.lane)||['RUNNING','VERIFYING','REPAIRING'].includes(n.status));}
 function nodeHTML(n){return `<strong>${esc(n.title)}</strong><span class="flow-state">${esc(icons[n.status]||'·')} ${esc(states[n.status]||state(n.status))}</span><small>${esc(n.kind==='resource'?`앞선 작업 ${n.ahead_count||0}개`:data.lanes[n.lane])}${n.revision===null?'':` · 수정 ${n.revision}`}${n.history==='current'?'':n.history==='invalidated'?' · 무효화':' · 이전 기록'}</small><small>${n.elapsed_ms===null?'시간 미확인':Math.round(n.elapsed_ms)+'ms'} · ${n.cost_usd===null?'비용 미확인':usd(n.cost_usd)+' API 추정'}</small>${expanded.has(n.lane)?`<small>${esc(labels[n.role]||n.role||data.lanes[n.lane])} · ${n.elapsed_ms===null?'시간 미확인':Math.round(n.elapsed_ms)+'ms'} · ${n.cost_usd===null?'비용 미확인':usd(n.cost_usd)+' 추정'}</small>`:''}`;}
 function paint(){const host=$('#research-flow');if(!host||!data)return;updates++;
  const current=data.current_ids.map(id=>data.nodes.find(n=>n.id===id)?.title).filter(Boolean).slice(0,2).join(' · ');
  $('#flow-status').textContent=`${current||states[data.control_status]||state(data.control_status||data.status)} · 진행 항목 ${data.counts.running} · 대기 ${data.counts.queued} · 확인 필요 ${data.counts.review}`;
  $('#flow-count').textContent=`${data.visible_total}개 중 ${offset+1}–${Math.min(offset+data.limit,data.visible_total)} · 화면 밖 연결 ${data.boundary_edges}${data.irrelevant_sources?' · 제외한 문헌 '+data.irrelevant_sources+'개':''}`;
  $('#flow-prev').disabled=!offset;$('#flow-next').disabled=data.next_offset===null;
  const visible=shown(),ids=new Set(visible.map(n=>n.id)),nodeHost=host.querySelector('.flow-nodes');
  for(const button of [...nodeHost.children])if(!ids.has(button.dataset.node))button.remove();
  for(const n of visible){let button=[...nodeHost.children].find(b=>b.dataset.node===n.id);if(!button){button=document.createElement('button');button.className='flow-node';button.dataset.node=n.id;button.dataset.kind=n.kind;button.dataset.lane=n.lane;if(n.role)button.dataset.role=n.role;button.onclick=()=>select(n.id);button.onkeydown=key;nodeHost.append(button);}
   const html=nodeHTML(n);if(button.innerHTML!==html)button.innerHTML=html;button.dataset.status=n.status;button.dataset.history=n.history;button.classList.toggle('current-path',n.on_current_path);button.classList.toggle('flow-neighbor',n.selected_neighbor);button.classList.toggle('flow-selected',n.id===selected);button.title=n.title+' · '+n.ref;button.setAttribute('aria-label',`${n.title} · ${states[n.status]||state(n.status)} · ${data.lanes[n.lane]}`);
  }
  const signature=data.layout_revision+'|'+[...expanded].sort().join(',');
  if(host.dataset.layout!==signature){layout(visible);host.dataset.layout=signature;}
  host.querySelectorAll('.flow-edge').forEach(e=>e.classList.toggle('flow-highlight',data.nodes.some(n=>n.id===e.dataset.source&&(n.on_current_path||n.selected_neighbor))&&data.nodes.some(n=>n.id===e.dataset.target&&(n.on_current_path||n.selected_neighbor))));host.dataset.layoutRuns=layoutRuns;host.dataset.updates=updates;
  if(app.control&&app.rid===rid){app.control.status=data.control_status;app.control.version=data.control_version;}
 }
 function layout(visible){layoutRuns++;const host=$('#research-flow'),laneIds=data.lane_order,laneHeight={};
  for(const n of visible)if(!positions.has(n.id)){let slot=0;while([...positions.values()].some(p=>p.lane===n.lane&&p.level===n.level&&p.slot===slot))slot++;positions.set(n.id,{lane:n.lane,level:n.level,slot});}
  for(const lane of laneIds)laneHeight[lane]=Math.max(118,...visible.filter(n=>n.lane===lane).map(n=>(positions.get(n.id).slot+1)*(expanded.has(lane)?148:116)+24));
  let top=0;const laneTop={};host.querySelector('.flow-lanes').innerHTML=laneIds.map(lane=>{laneTop[lane]=top;const text=`<section class="flow-lane" aria-label="${esc(data.lanes[lane])}"><button data-flow-lane="${lane}" aria-expanded="${expanded.has(lane)}">${esc(data.lanes[lane])} ${expanded.has(lane)?'−':'+'}</button></section>`;top+=laneHeight[lane];return text;}).join('');
  host.querySelectorAll('.flow-lane').forEach((section,i)=>{section.style.top=laneTop[laneIds[i]]+'px';section.style.height=laneHeight[laneIds[i]]+'px';});host.querySelectorAll('[data-flow-lane]').forEach(b=>b.onclick=()=>{expanded.has(b.dataset.flowLane)?expanded.delete(b.dataset.flowLane):expanded.add(b.dataset.flowLane);host.dataset.layout='';paint();});
  const width=Math.max(600,Math.max(...visible.map(n=>n.level),0)*220+380);const diagram=host.querySelector('.flow-diagram');diagram.style.width=width+'px';diagram.style.height=top+'px';
  for(const b of host.querySelectorAll('.flow-node')){const p=positions.get(b.dataset.node);p.x=150+p.level*220;p.y=laneTop[p.lane]+12+p.slot*(expanded.has(p.lane)?148:116);b.style.left=p.x+'px';b.style.top=p.y+'px';}
  const svg=host.querySelector('.flow-edges');svg.setAttribute('viewBox',`0 0 ${width} ${top}`);svg.setAttribute('width',width);svg.setAttribute('height',top);
  const shownIds=new Set(visible.map(n=>n.id)),forward=new Map();for(const e of data.edges){if(!forward.has(e.source))forward.set(e.source,[]);forward.get(e.source).push(e);}
  const rendered=[],used=new Set();for(const edge of data.edges){if(!shownIds.has(edge.source))continue;if(edge.source.startsWith('contract:')&&edge.target.startsWith('artifact:')&&data.edges.some(x=>x.target===edge.target&&x.source.startsWith('tool:')))continue;const pending=[edge],seen=new Set();while(pending.length){const e=pending.pop();if(seen.has(e.target))continue;seen.add(e.target);if(!shownIds.has(e.target)){pending.push(...(forward.get(e.target)||[]));continue;}const id=edge.source+'>'+e.target+'>'+edge.relation;if(used.has(id))continue;used.add(id);const a=positions.get(edge.source),b=positions.get(e.target),x=a.x+196,y=a.y+44,tx=b.x,ty=b.y+44;rendered.push(`<path class="flow-edge" data-source="${esc(edge.source)}" data-target="${esc(e.target)}" data-relation="${esc(edge.relation)}" d="M${x},${y} C${x+32},${y} ${tx-32},${ty} ${tx},${ty}" marker-end="url(#flow-arrow)"><title>${esc(relations[edge.relation]||edge.relation)}</title></path>`);}}
  svg.innerHTML=`<defs><marker id="flow-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>`+rendered.join('');
 }
 function key(e){if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;const buttons=[...$('#research-flow').querySelectorAll('.flow-node')],index=buttons.indexOf(e.currentTarget);e.preventDefault();buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:Math.max(0,Math.min(buttons.length-1,index+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)))].focus();}
 async function select(id){if(options.onSelect){selected=id;await refresh();return options.onSelect(id);}generation++;busy=false;selected=id;const research=rid,version=generation;await refresh();if(generation!==version||app.rid!==research||app.tab!=='flow')return;try{const value=await api(`/api/control/research/${encodeURIComponent(research)}/flow-node?id=${encodeURIComponent(id)}`);if(generation!==version||app.rid!==research||app.tab!=='flow')return;inspect(value.title,fields(value.summary)+`<div class="flow-detail" id="flow-detail">${fields(value.detail)}</div>${value.repair_contract?`<section><h3>원본 분석 계약</h3>${fields(value.repair_contract)}</section><section><h3>분석 결과</h3>${fields(value.analysis_result)}</section><section><h3>검증 결과</h3>${fields(value.verifier_result)}</section>`:''}${value.artifacts?.length?table(['산출물','유형','상태'],value.artifacts.map(a=>[esc(a.id),esc(a.type),tag(a.status)])):''}`);}catch(e){message(e.message);}}
 async function refresh(){if(busy||app.rid!==rid||app.tab!=='flow'||!$('#research-flow'))return;busy=true;const research=rid,version=generation;try{if(app.control?.snapshot&&['RUNNING','STARTING','RESUMING','PAUSE_REQUESTED','STOP_REQUESTED'].includes(app.control.status)){const control=await api(`/api/control/research/${encodeURIComponent(research)}/control?summary=1`);if(generation!==version)return;Object.assign(app.control,control);}const result=await api(`/api/control/research/${encodeURIComponent(research)}/flow?view=${view}&offset=${offset}&limit=${app.settings.low_spec?60:120}${options.lane?'&lane='+encodeURIComponent(options.lane):''}${selected?'&selected='+encodeURIComponent(selected):''}`);if(generation!==version||app.rid!==research||app.tab!=='flow')return;if(!data&&options.expandAgents)expanded=new Set(result.lane_order);data=result;paint();}catch(e){message(e.message);}finally{if(generation===version)busy=false;}}
 return {mount,refresh};
})();
