// 실제 Chrome에서 초보자 흐름을 검사한다. 외부 API는 명시적 모의 전송이다.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');
const {chromium}=require('./browser_runtime.cjs');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'build/beginner-v4/browser',crypto.randomUUID());
const out=path.join(root,'output/playwright/beginner_v4');fs.mkdirSync(folder,{recursive:true});fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],shots=[];let browser,child;
function save(file,value){const text=JSON.stringify(value,null,2)+'\n';if(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(text))throw Error('UTF8');fs.writeFileSync(file,Buffer.from(text,'utf8'));}
function check(name,value){checks.push({name,passed:!!value});save(path.join(folder,'progress.json'),{checks,errors});if(!value)throw Error(name);}
async function main(){
 const env={...process.env};for(const key of Object.keys(env))if(key.endsWith('API_KEY'))delete env[key];
 child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-X','utf8','qa/beginner_v4_browser_fixture.py',folder],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env});
 let stderr='';child.stderr.on('data',v=>stderr+=v);
 const url=await new Promise((resolve,reject)=>{let text='';child.stdout.on('data',v=>{text+=v;const m=text.match(/http:\/\/127\.0\.0\.1:\d+\/#bootstrap=[A-Za-z0-9_-]{43}/);if(m)resolve(m[0]);});child.on('exit',()=>reject(Error(stderr.slice(-1200))));setTimeout(()=>reject(Error('서버 시간 초과')),15000).unref();});
 const origin=new URL(url).origin;
 browser=await chromium.launch({channel:'chrome',headless:process.env.PROBE_UI_TEST_HEADED!=='1'});
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.setDefaultTimeout(15000);page.on('pageerror',x=>errors.push(x.message));
 page.on('request',r=>{if(!r.url().startsWith(origin+'/')&&!r.url().startsWith('blob:'))errors.push('외부 요청 '+new URL(r.url()).origin);});
 await page.goto(url);await page.locator('#research-table').waitFor();check('자동 인증 및 티켓 제거',!page.url().includes('bootstrap'));
 check('상단 새 연구 제거',await page.locator('.topbar #new-research').count()===0);
 check('연구 메뉴',await page.locator('[data-view="research"]').innerText()==='연구');
 await page.locator('#tutorial-skip').click();await page.locator('#tutorial-card').waitFor({state:'detached'});
 await page.locator('#list-new').click();await page.locator('#with-explanations').waitFor();check('설명 선택 먼저 표시',await page.locator('#research-form').count()===0);
 await page.locator('#dismiss-explanations').check();await page.locator('#with-explanations').click();await page.locator('#research-form').waitFor();
 check('첫 장 고급 설정 숨김',!await page.locator('#research-advanced').isVisible());
 check('자동 모델 선택',await page.locator('[name="model_profile_id"]').inputValue()==='m');
 check('기본 예산 실제 값',await page.locator('[name="run_limit_usd"]').inputValue()==='0.1');
 check('연구 입력에는 설명 대신 필수 항목만 표시',await page.locator('.field-explanation').count()===0&&await page.locator('[name=question]').locator('..').locator('.required-mark').count()===1);
 check('보고서 형식 선택 없음',await page.locator('[name="report_format"]').count()===0);
 await page.locator('[name="question"]').fill('공개 자료의 관계를 검토해 주세요.');await page.locator('#research-next').click();
 await page.locator('#more-models').click();
 check('선택 모델 제공사 그룹 복귀',await page.locator('.provider-group input[value="m"]').count()===1);
 check('고정 중복 없음',await page.locator('#selected-models input').count()===0);
 check('전체 모델 선택 행 중복 없음',await page.locator('input[name="catalog-model"][value="m"]').count()===1);
 await page.locator('#more-models').click();check('접으면 선택 모델 고정',await page.locator('#selected-models input[value="m"]').count()===1);
 await page.locator('[name=search_policy]').selectOption('DISABLED');await page.locator('#research-next').click();
 await page.locator('#research-start').click();await page.locator('#run-content').waitFor();
 check('질문 정리와 보고서의 실제 모의 전송',JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).length===2);
 check('근거 부족 정직한 상태',await page.locator('#content').innerText().then(t=>t.includes('확인 필요')));
 await page.locator('#run-back').click();await page.locator('#list-new').click();await page.locator('#research-form').waitFor();
 check('안내 다시 묻지 않기 저장',await page.locator('#with-explanations').count()===0);
 await page.locator('[name="question"]').fill('1981~2000년과 2001~2020년의 전 지구 연간 기온 편차 평균을 비교해 주세요.');
 await page.locator('#research-next').click();await page.locator('#research-next').click();await page.locator('#research-start').click();await page.locator('.conclusion-card').waitFor();
 check('한정 프로필 결론 카드',await page.locator('.conclusion-card h3').count()===6);
 check('현재 결론',await page.locator('.conclusion-card').innerText().then(t=>t.includes('현재 결론')));
 const before=JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).length;
 const recalculate=page.waitForResponse(r=>r.url().endsWith('/recalculate')&&r.request().method()==='POST');
 await page.locator('#profile-recalculate').click();const checked=await recalculate;
 save(path.join(folder,'recalculate-response.json'),{status:checked.status(),body:await checked.json()});
 check('계산 재확인 API 성공',checked.ok());await page.locator('#notice[data-status="success"]').waitFor();
 check('계산 확인 유료 호출 없음',JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).length===before);
 const revision=await page.evaluate(async()=>{const r=await fetch('/qa/revise',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':app.csrf},body:'{}'});return r.status;});check('오프라인 원본 수정 주입',revision===200);
 await page.locator('#profile-refresh').click();await page.getByText('다시 확인 필요',{exact:true}).waitFor();
 check('변경 영향 표시',await page.locator('.conclusion-card').innerText().then(t=>t.includes('사용한 자료가 바뀌어')));
 const secondCheck=page.waitForResponse(r=>r.url().endsWith('/recalculate')&&r.request().method()==='POST');await page.locator('#profile-recalculate').click();const secondResponse=await secondCheck;save(path.join(folder,'recalculate-source-response.json'),{status:secondResponse.status(),body:await secondResponse.json()});await page.getByText('현재 결론',{exact:true}).waitFor().catch(async e=>{save(path.join(folder,'failed-screen.json'),{body:await page.locator('#content').innerText(),notice:await page.locator('#notice').innerText()});throw e;});
 check('다시 검증한 현재 결론',await page.locator('.conclusion-card').innerText().then(t=>t.includes('현재 결론')));
 check('이전 결론 보존',await page.locator('.conclusion-card details p').count()>=2);
 check('재검증도 모의 API 추가 없음',JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).length===before);
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-primary-tab=report]').click();await page.locator('[data-pdf]').click();const download=await downloadPromise;await download.saveAs(path.join(folder,'report.pdf'));check('실제 PDF 생성',fs.readFileSync(path.join(folder,'report.pdf')).subarray(0,5).toString()==='%PDF-');
 await page.screenshot({path:path.join(out,'conclusion.png')});shots.push('output/playwright/beginner_v4/conclusion.png');
 await page.locator('#run-back').click();await page.locator('[data-rename]').first().click();await page.locator('#rename-form input').fill('수정한 연구 제목');await page.locator('#rename-form button').click();await page.getByText('수정한 연구 제목',{exact:true}).waitFor();
 await page.locator('[data-trash]').first().click();await page.locator('[data-filter="trash"]').click();await page.locator('[data-restore]').waitFor();check('휴지통 이동',await page.locator('[data-restore]').count()===1);
 await page.locator('[data-restore]').click();check('복원 후 휴지통 비어 있음',await page.locator('.empty').innerText().then(t=>t.includes('휴지통이 비어')));
 await page.locator('[data-view="settings"]').click();await page.locator('#settings-tab-help').click();await page.locator('#show-explanations').waitFor();
 check('기본 설정에 호출별 단가 한도 없음',await page.locator('[name="request_limit_usd"]').count()===0);
 await page.locator('#show-explanations').uncheck();await page.locator('#show-explanations').waitFor();check('설명 표시 변경 가능',!await page.locator('#show-explanations').isChecked());
 await page.locator('#settings-tab-connections').click();await page.locator('[data-connection-check]').click();await page.locator('#connection-check').waitFor();check('연결 검사 연구 설정 없음',await page.locator('#connection-check [name="question"],#connection-check [name="search_required"]').count()===0);
 await page.locator('#connection-check button.primary').click();await page.getByText('AI 응답 확인 완료',{exact:true}).waitFor();check('독립 연결 검사 성공',JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).at(-1).connection_check);
 await page.locator('#editor-close').click();await page.locator('#settings-tab-help').click();await page.locator('#replay-tutorial').click();await page.locator('#tutorial-coach').waitFor();check('튜토리얼 다시 보기',await page.locator('#tutorial-coach').count()===1);await page.locator('#tutorial-coach-close').click();await page.locator('#tutorial-coach').waitFor({state:'detached'});await page.locator('[data-view="settings"]').click();await page.locator('#settings-tab-help').click();await page.locator('#full-guidebook').waitFor();
 await page.locator('#full-guidebook').click();check('전체 사용 안내',await page.locator('[data-guide-topic]').count()===41&&await page.locator('[data-guide-chapter]').count()===9);await page.locator('#inspector-close').click();
 await page.evaluate(()=>document.documentElement.style.zoom='2');await page.setViewportSize({width:1280,height:900});
 check('200% 확대 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 await page.screenshot({path:path.join(out,'settings-200.png')});shots.push('output/playwright/beginner_v4/settings-200.png');
 check('브라우저 오류·외부 전송 없음',errors.length===0);
 const result={execution:'REAL_CHROME_WITH_MOCK_HTTP',checks,errors,shots,folder:path.relative(root,folder).replaceAll('\\','/')};
 save(path.join(root,'qa/beginner_v4_browser_results.json'),result);process.stdout.write(JSON.stringify({checks:checks.length,passed:checks.every(c=>c.passed),errors,folder:result.folder})+'\n');
}
main().catch(e=>{save(path.join(root,'qa/beginner_v4_browser_results.json'),{checks,errors,error:e.message,folder:path.relative(root,folder)});process.stderr.write(e.stack+'\n');process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(child)child.kill();});
