// 큰 합성 이력에서 실제 Chrome의 상태 갱신·DOM·유휴 자원을 측정한다.
'use strict';
const fs=require('fs'),path=require('path'),{spawn,spawnSync}=require('child_process');
const {chromium}=require('./browser_runtime.cjs');
const root=path.resolve(__dirname,'..'),folder=process.argv[2]||'build/flow-large-fixture',fixture=JSON.parse(fs.readFileSync(path.join(root,folder,'fixture.json'),'utf8'));
const python=path.join(root,'.venv/Scripts/python.exe'),env={...process.env};for(const k of Object.keys(env))if(/API_KEY|TOKEN|SECRET/.test(k))delete env[k];
const server=spawn(python,['-X','utf8','qa/flow_visual_fixture.py',folder],{cwd:root,env,windowsHide:true});
let browser,stdout='';const privateValues=[],checks=[],errors=[],outside=[],result={execution:'SYNTHETIC_OFFLINE_CHROME',live_efficacy:'NOT_VALIDATED'};
function check(name,pass){if(!pass)throw Error('검사 실패: '+name);checks.push({name,passed:true});}
function save(value){const s=JSON.stringify(value,null,2)+'\n';if(/[\uD800-\uDFFF]/u.test(s)||privateValues.some(v=>s.includes(v)))throw Error('검증 기록 차단');fs.writeFileSync(path.join(root,'qa/performance/low_spec/flow_large.json'),Buffer.from(s,'utf8'));}
async function main(){const url=await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{stdout+=b;const m=stdout.match(/http:\/\/127\.0\.0\.1:\d+\/#bootstrap=([A-Za-z0-9_-]+)/);if(m){privateValues.push(m[1]);resolve(m[0]);}});server.on('exit',c=>reject(Error('서버 종료 '+c)));setTimeout(()=>reject(Error('서버 시작 시간 초과')),20000).unref();});
 const origin=new URL(url).origin;browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();page.setDefaultTimeout(20000);
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin+'/'))outside.push(r.url());});await page.goto(url);await page.locator('#research-table').waitFor();
 const begin=performance.now();await page.goto(origin+'/#research/'+fixture.repair+'/flow');await page.locator('.relationship-details summary').waitFor();await page.locator('.relationship-details summary').click();await page.locator('.flow-node').first().waitFor();result.initial_map_render_ms=performance.now()-begin;
 const metrics=await page.evaluate(async rid=>await(await fetch('/api/control/research/'+rid+'/flow?view=all&limit=150')).json(),fixture.repair);result.total_nodes=metrics.total_nodes;result.source_fingerprint=fixture.source_fingerprint;result.edge_lower_bound=fixture.edge_lower_bound;result.total_edges=metrics.boundary_edges+metrics.edges.length;
 check('100개 이상의 실제·합성 저장 노드',result.total_nodes>100);check('복구 분기를 포함한 다섯 역할',await page.locator('[data-flow-lane]').count()===5);
 let update=Number(await page.locator('#research-flow').getAttribute('data-updates')),start=performance.now();await page.locator('[data-flow-view=all]').click();await page.waitForFunction(v=>Number(document.querySelector('#research-flow').dataset.updates)>v,update);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));result.full_graph_render_ms=performance.now()-start;
 const id='hypothesis:'+fixture.hypothesis,node=page.locator('.flow-node').filter({hasText:'합성 화면 상태 변경 검사'});check('갱신할 가설 표시',await node.count()===1);await node.evaluate(n=>window.__flowProbeNode=n);const layouts=await page.locator('#research-flow').getAttribute('data-layout-runs');
 const changed=spawnSync(python,['-X','utf8','qa/flow_large_probe.py','--update','--folder',folder],{cwd:root,env,windowsHide:true,encoding:'utf8'});check('정본 서비스로 상태 변경',changed.status===0);
 start=performance.now();await page.locator('#flow-refresh').click();await page.waitForFunction(id=>document.querySelector('[data-node="'+id+'"]')?.dataset.status==='QUEUED',id);result.update_single_node_ms=performance.now()-start;
 check('단일 상태 변경은 전체 배치 유지',await page.locator('#research-flow').getAttribute('data-layout-runs')===layouts);check('단일 상태 변경은 노드 DOM 유지',await node.evaluate(n=>n===window.__flowProbeNode));delete result.total_edges;
 update=Number(await page.locator('#research-flow').getAttribute('data-updates'));start=performance.now();await page.locator('[data-flow-view=current]').click();await page.waitForFunction(v=>Number(document.querySelector('#research-flow').dataset.updates)>v,update);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));result.current_path_render_ms=performance.now()-start;result.rendered_nodes=await page.locator('.flow-node').count();result.rendered_edges=await page.locator('.flow-edge').count();check('페이지 노드 120개 이하',result.rendered_nodes<=120);
 const client=await context.newCDPSession(page);await client.send('Performance.enable');const sample=async()=>Object.fromEntries((await client.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));const first=await sample();await page.waitForTimeout(60000);const last=await sample();result.idle_seconds=last.Timestamp-first.Timestamp;result.idle_cpu_with_map=(last.TaskDuration-first.TaskDuration)/result.idle_seconds*100;result.map_memory_mb=last.JSHeapUsedSize/1024**2;result.memory_scope='Chrome renderer JS heap · 전체 Chrome RSS/GPU 제외';check('유휴 60초 검사',result.idle_seconds>=59);check('지속 애니메이션 없음',await page.locator('.flow-node').first().evaluate(n=>getComputedStyle(n).animationName==='none'));check('브라우저 오류·외부 전송 없음',errors.length===0&&outside.length===0);
 result.checks=checks;save(result);console.log(JSON.stringify({passed:checks.length,...result}));
}
main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();});
