// 실제 인증된 Chrome에서 흐름·상세·키보드·대형 화면을 검사한다.
'use strict';
const fs=require('fs'),path=require('path'),{spawn}=require('child_process');
const {chromium}=require('./browser_runtime.cjs');
const root=path.resolve(__dirname,'..'),folder=process.argv[2]||'build/flow-ui-fixture';
const fixture=JSON.parse(fs.readFileSync(path.join(root,folder,'fixture.json'),'utf8'));
const output=path.join(root,'output/playwright/flow');fs.mkdirSync(output,{recursive:true});
const env={...process.env};for(const k of Object.keys(env))if(/API_KEY|TOKEN|SECRET/.test(k))delete env[k];
const child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-X','utf8','qa/flow_visual_fixture.py',folder],{cwd:root,windowsHide:true,env});
let browser,stdout='',stderr='';const checks=[],images=[],errors=[],logs=[],outside=[],requests=[],privateValues=[],timings=[];
const handoff=new Promise((resolve,reject)=>{child.stdout.on('data',b=>{stdout+=b;const m=stdout.match(/http:\/\/127\.0\.0\.1:\d+\/#bootstrap=([A-Za-z0-9_-]+)/);if(m){privateValues.push(m[1]);resolve(m[0]);}});child.stderr.on('data',b=>stderr+=b);child.on('exit',c=>reject(Error('검증 서버 종료 '+c)));setTimeout(()=>reject(Error('검증 서버 시작 시간 초과')),20000).unref();});
function check(name,pass,detail){if(!pass)throw Error('검사 실패: '+name);checks.push({name,passed:true,...detail});}
function save(file,value){const text=JSON.stringify(value,null,2)+'\n';if(/[\uD800-\uDFFF]/u.test(text)||privateValues.some(v=>text.includes(v)))throw Error('기록 인코딩·비밀 차단');fs.writeFileSync(file,Buffer.from(text,'utf8'));}
async function main(){const url=await handoff,origin=new URL(url).origin;browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();page.setDefaultTimeout(20000);
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')logs.push(m.text());});page.on('request',r=>{requests.push(new URL(r.url()).pathname);if(!r.url().startsWith(origin+'/'))outside.push(r.url());});
 page.on('response',r=>{if(r.status()>=400)logs.push(new URL(r.url()).pathname+' '+r.status());});
 await page.goto(url);await page.locator('#research-table').waitFor();const session=await page.evaluate(async()=>await(await fetch('/api/session')).json());privateValues.push(session.csrf);for(const c of await context.cookies())privateValues.push(c.value);
 check('시작 화면은 흐름 모듈을 읽지 않음',!requests.includes('/assets/research_flow.js'));
 async function open(rid,view='current'){const t=performance.now();await page.evaluate(({rid})=>{location.hash='#research/'+rid+'/flow';},{rid});await page.locator('.flow-node').first().waitFor();if(view!=='current'){await page.locator(`[data-flow-view=${view}]`).click();await page.waitForFunction(v=>document.querySelector(`[data-flow-view=${v}]`)?.getAttribute('aria-pressed')==='true',view);}timings.push({operation:'open_'+view,ms:performance.now()-t});}
 async function capture(name){const file=path.join(output,name+'.png');await page.screenshot({path:file});images.push(path.relative(root,file).replaceAll('\\','/'));check(name+' 본문 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}
 await open(fixture.a);check('한 화면의 네 가지 보기',await page.locator('[data-flow-view]').count()===4);check('다섯 개 논리 역할',await page.locator('[data-flow-lane]').count()===5);check('노드에 상태 이름 표시',await page.locator('.flow-state').first().innerText());check('의미별 관계 범례',await page.locator('.flow-legend [data-relation]').count()===10);check('전체 백분율을 만들지 않음',!/%/.test(await page.locator('#flow-status').innerText()));
 check('읽기 전에 상세 API를 호출하지 않음',!requests.some(p=>p.endsWith('/flow-node')));await capture('현재-연구');
 const first=page.locator('.flow-node').first();await first.focus();await page.keyboard.press('ArrowRight');check('키보드로 다음 노드 이동',await page.evaluate(()=>document.activeElement.classList.contains('flow-node')));check('키보드 초점 테두리 표시',await page.evaluate(()=>parseFloat(getComputedStyle(document.activeElement).outlineWidth)>=2));check('노드의 접근성 이름',await page.locator('.flow-node').first().getAttribute('aria-label').then(v=>Boolean(v)));await page.keyboard.press('Home');await page.keyboard.press('Enter');await page.locator('#inspector[open]').waitFor();check('선택한 객체만 상세 조회',requests.some(p=>p.endsWith('/flow-node')));await capture('상세');await page.locator('#inspector-close').click();await page.waitForFunction(()=>document.querySelector('#inspector-content').children.length===0);check('상세 닫기 후 DOM 해제',await page.locator('#inspector-content > *').count()===0);const before=await page.locator('#research-flow').getAttribute('data-layout-runs');
 await page.locator('#flow-refresh').click();await page.waitForFunction(()=>Number(document.querySelector('#research-flow').dataset.updates)>=3);check('같은 관계는 재배치하지 않음',await page.locator('#research-flow').getAttribute('data-layout-runs')===before);
 await page.locator('[data-flow-view=all]').click();await page.waitForTimeout(150);check('페이지 노드 제한',await page.locator('.flow-node').count()<=120);await capture('전체-연구');
 await open(fixture.b,'all');await page.waitForTimeout(150);check('무효화된 결과 유지',await page.locator('.flow-node[data-history=invalidated]').count()>0);await capture('무효화');
 await open(fixture.repair,'recovery');await page.waitForTimeout(150);check('복구와 교체 연결',await page.locator('.flow-edge[data-relation=repairs],.flow-edge[data-relation=supersedes]').count()>0);check('원본 기록 유지',await page.locator('.flow-node[data-history=superseded]').count()>0);const repair=page.locator('.flow-node').filter({hasText:'필수 재검증'}).first();await repair.click();await page.locator('#inspector[open]').waitFor();check('원본 계약·분석·검증 구분',await page.locator('#inspector-content').innerText().then(t=>['원본 분석 계약','분석 결과','검증 결과'].every(s=>t.includes(s))));await capture('복구-상세');await page.locator('#inspector-close').click();
 await context.grantPermissions([]);await page.emulateMedia({reducedMotion:'reduce'});check('모션 줄이기 적용',await page.locator('.flow-node').first().evaluate(n=>getComputedStyle(n).animationName==='none'));await page.setViewportSize({width:390,height:844});await capture('모바일');await repair.click();await page.locator('#inspector[open]').waitFor();await capture('모바일-상세');await page.locator('#inspector-close').click();
 await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.style.zoom='2');await capture('200퍼센트-CSS-확대');check('확대된 화면에서도 닫기 접근',await repair.isEnabled());await page.evaluate(()=>document.documentElement.style.zoom='');
 check('브라우저 오류 없음',errors.length===0,{errors});if(logs.length)console.error(logs.map(s=>privateValues.reduce((v,k)=>v.replaceAll(k,'[제거]'),s)).join('\n'));check('CSP·콘솔 오류 없음',logs.length===0,{logs});check('외부 전송 없음',outside.length===0);const client=await context.newCDPSession(page);await client.send('Performance.enable');const metrics=await client.send('Performance.getMetrics');const heap=metrics.metrics.find(m=>m.name==='JSHeapUsedSize')?.value;
 save(path.join(output,'result.json'),{execution:'OFFLINE_FAKE_PROVIDER_CHROME',checks,timings,images,flow_heap_bytes:heap,request_count:requests.length,live_performance:'NOT_VALIDATED'});console.log(JSON.stringify({passed:checks.length,timings,heap_bytes:heap}));
}
main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();child.kill();});
