// 실제 Chrome에서 연구 설정·튜토리얼·초안 복구를 검사한다. 모델 호출은 로컬 모의 전송만 허용한다.
const {chromium}=require('./browser_runtime.cjs');
const {spawn}=require('child_process'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'build/research-wizard/browser',crypto.randomUUID()),out=path.join(root,'output/playwright/research-wizard');
fs.mkdirSync(folder,{recursive:true});fs.mkdirSync(out,{recursive:true});
let child,browser,testPage;const checks=[],errors=[];
function save(file,value){const text=JSON.stringify(value,null,2)+'\n';if(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(text))throw Error('UTF8');fs.writeFileSync(file,Buffer.from(text,'utf8'));}
function check(name,passed){checks.push({name,passed:!!passed});save(path.join(folder,'progress.json'),{checks,errors});if(!passed)throw Error(name);}
async function main(){
 const env={...process.env};for(const key of Object.keys(env))if(key.endsWith('API_KEY'))delete env[key];
 child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-X','utf8','qa/beginner_v4_browser_fixture.py',folder],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env});
 let stderr='';child.stderr.on('data',v=>stderr+=v);
 const url=await new Promise((resolve,reject)=>{let text='';child.stdout.on('data',v=>{text+=v;const m=text.match(/http:\/\/127\.0\.0\.1:\d+\/#bootstrap=[A-Za-z0-9_-]{43}/);if(m)resolve(m[0]);});child.on('exit',()=>reject(Error(stderr.slice(-1000))));setTimeout(()=>reject(Error('서버 시간 초과')),15000).unref();});
 const origin=new URL(url).origin;browser=await chromium.launch({channel:'chrome',headless:process.env.HTRSA_UI_TEST_HEADED!=='1'});const page=testPage=await browser.newPage({viewport:{width:1280,height:850}});page.setDefaultTimeout(10000);
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin+'/')&&!r.url().startsWith('blob:'))errors.push('외부 요청');});
 await page.goto(url);await page.locator('#tutorial-card').waitFor();check('최초 실행 튜토리얼 참여 선택 표시',await page.locator('#tutorial-accept').isVisible());
 await page.locator('#tutorial-never').check();await page.locator('#tutorial-skip').click();await page.locator('#tutorial-card').waitFor({state:'detached'});await page.reload();await page.locator('#list-new').waitFor();check('다시 보지 않기 저장 및 자동 재표시 없음',await page.locator('#tutorial-card').count()===0);
 let releasePreference;const oldPreferenceResponse=page.waitForResponse(r=>r.url().endsWith('/api/control/preferences')&&r.request().method()==='POST');let holdPreference=true;
 await page.route('**/api/control/preferences',async route=>{if(route.request().method()==='POST'&&holdPreference){holdPreference=false;await new Promise(r=>releasePreference=r);}await route.continue();});
 await page.locator('#list-new').click();await page.locator('#without-explanations').click();await page.locator('#editor-close').click();await page.locator('[data-view=settings]').click();await page.locator('#settings-tab-help').waitFor();await page.locator('[data-view=research]').click();await page.locator('#list-new').click();await page.locator('#without-explanations').waitFor();
 check('이전 안내 저장 대기 중 재열기',await page.locator('#without-explanations').isVisible());releasePreference();await oldPreferenceResponse;await page.waitForTimeout(80);
 check('이전 안내 응답이 새 화면을 닫지 않음',await page.locator('#without-explanations').isVisible());await page.unroute('**/api/control/preferences');
 await page.locator('#dismiss-explanations').check();await page.locator('#without-explanations').click();await page.locator('#research-form').waitFor();
 check('세 단계 진행 표시',await page.locator('.research-progress [data-step]').count()===3);check('첫 장에만 주제 질문 파일',await page.locator('[name=title]').isVisible()&&await page.locator('[name=question]').isVisible()&&await page.locator('[name=attachment_files]').isVisible()&&!await page.locator('#research-start').isVisible());
 await page.locator('[name=title]').fill('파일 유지 연구');await page.locator('[name=question]').fill('측정값의 관계를 검토해 주세요.');
 await page.locator('[name=attachment_files]').setInputFiles({name:'자료.csv',mimeType:'text/csv',buffer:Buffer.from('x,y\n1,2\n2,4\n3,6\n','utf8')});await page.getByText('내용 읽기 완료',{exact:false}).waitFor();
 await page.locator('#research-next').click();check('둘째 장에 모델 성능 검색 예산',await page.locator('#research-model-picker').isVisible()&&await page.locator('#performance').isVisible()&&await page.locator('[name=search_policy]').isVisible()&&await page.locator('[name=run_limit_usd]').isVisible());
 const active=page.locator('.model-option[data-active=true]').first();check('연결 모델 활성화 초록색',await active.locator('.model-activation').innerText()==='활성화'&&await active.locator('.model-activation').evaluate(e=>getComputedStyle(e).color)==='rgb(23, 100, 61)');
 const inactive=page.locator('.model-option[data-active=false]').first();check('미연결 모델 비활성화 빨간색',await inactive.locator('.model-activation').innerText()==='비활성화'&&await inactive.locator('.model-activation').evaluate(e=>getComputedStyle(e).color)==='rgb(179, 38, 30)');check('미연결 모델 선택 차단',await inactive.locator('input').isDisabled());
 await page.locator('#performance').focus();await page.keyboard.press('Home');check('성능 low',await page.locator('#performance-detail').innerText()==='low');await page.keyboard.press('End');check('성능 max',await page.locator('#performance-detail').innerText()==='max');
 await page.locator('[name=run_limit_usd]').fill('0.08');await page.locator('#research-next').click();
 check('마지막 장 고급 설정과 시작',await page.locator('#research-advanced').isVisible()&&await page.locator('#research-start').isVisible()&&!await page.locator('#research-next').isVisible());check('고급 설정 생략 안내는 튜토리얼에 제공',await page.evaluate(()=>HtrsaTutorialContent.coach_targets.research_start.targets[0].text.includes('건너뛰어도'))&&!await page.locator('#research-form').innerText().then(t=>t.includes('고급 설정은 건너뛰어도 됩니다.')));
 check('선택 자료 전송 기본값',await page.locator('[name=egress]').inputValue()==='selected');check('공개 검색 동의 별도 기본 꺼짐',!await page.locator('[name=public_search_consent]').isChecked());
 check('하단 연결 요구 문구 없음',!await page.locator('#research-form').innerText().then(t=>t.includes('이 제공사의 API 연결을 설정해 주세요')));
 await page.locator('#research-prev').click();await page.locator('#research-prev').click();check('이전 장 파일과 입력 유지',await page.locator('[name=title]').inputValue()==='파일 유지 연구'&&await page.locator('#attachment-list').innerText().then(t=>t.includes('자료.csv')));
 await page.locator('#research-tutorial').click();await page.locator('#tutorial-coach').waitFor();check('새 연구에서 실제 입력 안내 즉시 표시',await page.locator('#tutorial-coach').getAttribute('data-route')==='research_input'&&!await page.locator('#tutorial-popup').isVisible());
 await page.locator('.tutorial-menu>summary').click();await page.locator('#tutorial-restart').click();await page.locator('#provider-preparation').waitFor();await page.locator('#tutorial-coach-next').click();await page.locator('#connection-form').waitFor();
 await page.locator('#connection-form button.primary').focus();await page.waitForFunction(()=>$('#tutorial-coach')?.dataset.target==='#connection-form button.primary');await page.locator('#tutorial-coach-next').click();await page.locator('#list-new').waitFor();await page.locator('#list-new').click();await page.locator('#research-form').waitFor();
 await page.locator('#research-next').click();await page.locator('#research-next').click();await page.locator('#research-start').focus();await page.waitForFunction(()=>$('#tutorial-coach')?.dataset.target==='#research-start');
 check('튜토리얼 마지막 단계',await page.locator('#tutorial-coach-next').innerText()==='안내 마치기');await page.locator('#tutorial-coach-next').click();await page.locator('#tutorial-coach').waitFor({state:'detached'});check('튜토리얼 완료 후 양식 유지',await page.locator('#research-form').count()===1);
 check('핵심 네 과정 학습 완료 저장',await page.evaluate(()=>app.settings.preferences.tutorial_progress.status==='COMPLETED'&&app.settings.preferences.tutorial_progress.completed_steps.length===HtrsaTutorialContent.quick_start.length));
 await page.locator('#editor-close').click();await page.locator('[data-view=settings]').click();await page.locator('#settings-tab-help').click();await page.locator('#replay-tutorial').click();await page.locator('#tutorial-coach').waitFor();check('설정 튜토리얼 접근',await page.locator('#provider-preparation').isVisible());await page.locator('#tutorial-coach-close').click();await page.locator('#tutorial-coach').waitFor({state:'detached'});
 await page.locator('[data-view=research]').click();await page.locator('#list-new').click();await page.locator('#research-form').waitFor();check('다른 탭 이동 후 새 연구 재개',await page.locator('[name=title]').inputValue()==='파일 유지 연구');check('재개 후 첨부 유지',await page.locator('#attachment-list').innerText().then(t=>t.includes('자료.csv')));
 check('같은 실행 구간에서 닫기 재열기 유지',await page.evaluate(async()=>{$('#editor').close();await newResearch();await new Promise(r=>setTimeout(r,80));return Boolean($('#editor').open&&$('#research-form'));}));
 await page.route('**/api/control/attachments/*/upload',async route=>{await new Promise(r=>setTimeout(r,600));await route.continue();});
 await page.locator('[name=attachment_files]').setInputFiles({name:'늦은자료.txt',mimeType:'text/plain',buffer:Buffer.from('분석 참고 자료','utf8')});await page.getByText('업로드 중',{exact:false}).waitFor();
 await page.locator('#editor-close').click();await page.locator('#list-new').click();await page.locator('#research-form').waitFor();await page.locator('[name=question]').fill('재개한 연구의 새 질문');
 await page.waitForFunction(()=>$('#attachment-list').textContent.includes('늦은자료.txt')&&!$('#attachment-list').textContent.includes('업로드'));
 check('업로드 중 닫기 재개 후 상태 갱신',await page.locator('#attachment-list .attachment-row').count()===2);
 check('이전 업로드 완료가 새 질문을 덮어쓰지 않음',await page.locator('[name=question]').inputValue()==='재개한 연구의 새 질문'&&await page.evaluate(()=>app.researchDraft.question==='재개한 연구의 새 질문'));
 await page.unroute('**/api/control/attachments/*/upload');
 await page.locator('#editor-close').click();await page.reload();await page.locator('#list-new').waitFor();await page.locator('#list-new').click();await page.locator('#research-form').waitFor();check('새로고침 후 초안과 자료 복구',await page.locator('[name=title]').inputValue()==='파일 유지 연구'&&await page.locator('#attachment-list').innerText().then(t=>t.includes('자료.csv')));
 for(const width of [390,1280]){await page.setViewportSize({width,height:850});for(let step=0;step<3;step++){await page.evaluate(i=>$('#research-form').setResearchPage(i),step);check(`화면 ${width}px 장 ${step+1} 가로 넘침 없음`,await page.locator('#editor').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.screenshot({path:path.join(out,`page-${step+1}-${width}.png`)});}}
 await page.evaluate(()=>document.documentElement.style.zoom='2');check('200% 확대 가로 넘침 없음',await page.locator('#editor').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.evaluate(()=>document.documentElement.style.zoom='1');
 await page.locator('#editor-close').click();
 await page.route('**/api/control/research/draft',async route=>{if(route.request().method()==='GET')await new Promise(r=>setTimeout(r,500));await route.continue();});
 const lateDraftRequest=page.waitForRequest(r=>r.url().endsWith('/api/control/research/draft')&&r.method()==='GET');
 const lateDraftResponse=page.waitForResponse(r=>r.url().endsWith('/api/control/research/draft')&&r.request().method()==='GET');await page.evaluate(()=>{app.researchDraft=null;app.researchAttachments=null;});await page.locator('#list-new').click();await lateDraftRequest;await page.locator('[data-view=library]').click();await page.locator('#library-table').waitFor();await lateDraftResponse;await page.waitForTimeout(80);await page.unroute('**/api/control/research/draft');
 await page.waitForFunction(()=>app.view==='library'&&!$('#editor').open);check('늦은 초안 응답이 떠난 화면을 열지 않음',await page.locator('#research-form').count()===0);
 check('설정 중 모델 호출 없음',!fs.existsSync(path.join(folder,'observed.json'))||JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).length===0);
 check('브라우저 오류·외부 전송 없음',errors.length===0);
 save(path.join(folder,'result.json'),{execution:'REAL_CHROME_OFFLINE_FIXTURE',checks,errors,folder:path.relative(root,folder)});process.stdout.write(JSON.stringify({checks:checks.length,passed:true,folder:path.relative(root,folder)})+'\n');
}
main().catch(async e=>{const diagnostic=testPage?await testPage.evaluate(()=>({notice:$('#notice')?.textContent,view:app.view,hash:location.hash.startsWith('#bootstrap')?'bootstrap':location.hash,preferences:app.settings?.preferences,body:document.body.innerText.slice(0,1200)})).catch(()=>null):null;save(path.join(folder,'result.json'),{checks,errors,error:e.message,diagnostic});process.stderr.write(e.stack+'\n');process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(child)child.kill();});
