// 실제 Chrome에서 선택 설계·초안·제안·좁은 화면·결과 연결을 검사한다.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process'),{chromium}=require('./browser_runtime.cjs');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'build/design-v6/browser',crypto.randomUUID()),shots=path.join(root,'output/playwright/design-v6',path.basename(folder));
const checks=[],errors=[];let child,browser,context;
function check(name,value){checks.push({name,passed:!!value});if(!value)throw Error(name);}
function save(result){const text=JSON.stringify(result,null,2)+'\n';if(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(text))throw Error('UTF-8 검사 실패');fs.writeFileSync(path.join(folder,'result.json'),Buffer.from(text,'utf8'));}
async function main(){
 fs.mkdirSync(folder,{recursive:true});fs.mkdirSync(shots,{recursive:true});const env={...process.env};for(const key of Object.keys(env))if(key.endsWith('API_KEY'))delete env[key];
 child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-B','-X','utf8','qa/research_design_browser_fixture.py',folder],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env});
 let stderr='';child.stderr.on('data',v=>stderr+=v);
 const url=await new Promise((resolve,reject)=>{let out='';child.stdout.on('data',v=>{out+=v;const match=out.match(/http:\/\/127\.0\.0\.1:\d+\/#bootstrap=[A-Za-z0-9_-]{43}/);if(match)resolve(match[0]);});child.on('exit',()=>reject(Error(stderr.slice(-2000))));setTimeout(()=>reject(Error('검사 서버 준비 시간 초과')),30000).unref();});
 const profile=path.join(folder,'chrome-profile');fs.mkdirSync(path.join(profile,'Default'),{recursive:true});
 const prefs=JSON.stringify({partition:{default_zoom_level:{x:process.env.HTRSA_DESIGN_ZOOM==='1'?Math.log(2)/Math.log(1.2):0}}});Buffer.from(prefs,'utf8').toString('utf8');fs.writeFileSync(path.join(profile,'Default/Preferences'),prefs);
 context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:false,viewport:{width:1280,height:900}});
 const page=await context.newPage();page.setDefaultTimeout(20000);const origin=new URL(url).origin;
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin+'/')&&!r.url().startsWith('blob:'))errors.push('외부 요청');});
 await page.goto(url);await page.locator('#list-new').waitFor();const before=await page.evaluate(()=>api('/qa/state'));
 if(process.env.HTRSA_DESIGN_ZOOM==='1')check('Chrome 자체 200% 확대',await page.evaluate(()=>devicePixelRatio===2&&innerWidth===640));
 await page.locator('#list-new').click();await page.locator('#research-input-mode').waitFor();
 check('간단 입력에는 기존 주제·질문과 선택 버튼만 추가',await page.locator('[name=title]').count()===1&&await page.locator('[name=question]').count()===1&&!await page.locator('#design-body').isVisible());
 await page.locator('[name=title]').fill('상세 입력 검사');await page.locator('[name=question]').fill('자료를 살펴본다');
 await page.locator('[name=attachment_files]').setInputFiles({name:'측정.csv',mimeType:'text/csv',buffer:Buffer.from('x,y\n1,2\n2,3\n','utf8')});
 await page.waitForFunction(()=>app.researchAttachments?.some(a=>a.status==='READ'));
 const attachmentID=await page.evaluate(()=>app.researchAttachments.find(a=>a.status==='READ').attachment_id);
 await page.screenshot({path:path.join(shots,'01-simple.png')});
 await page.locator('[name=design_mode][value=detailed]').focus();await page.keyboard.press('Space');check('키보드로 맞춤 설계 선택',await page.locator('[name=design_mode][value=detailed]').isChecked());
 check('6개 섹션 중 처음 2개만 펼침',await page.locator('[data-section]').count()===6&&await page.locator('[data-section][open]').count()===2);
 await page.locator('[data-field=purpose]').fill('관측 조건 비교');await page.locator('[data-add-var=fixed]').click();await page.locator('[data-v-name]').fill('물의 양');await page.locator('.design-card-details>summary').click();
 await page.locator('[data-v-detail=maintain]').fill('같은 도구로 양을 재기');await page.locator('[data-v-detail=check]').fill('측정한 양을 기록하기');
 const variableID=await page.locator('[data-var]').getAttribute('data-var');
 check('통제 계획의 유지·확인 방법 입력 가능',await page.locator('[data-v-detail=maintain]').inputValue()==='같은 도구로 양을 재기');
 await page.locator('[data-v-name]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(shots,'02-controls.png')});
 await page.locator('[name=design_mode][value=simple]').check();check('일반 설정에 저장된 조건 수 표시',await page.locator('#design-mode-count').innerText().then(s=>s.includes('2개')));
 await page.screenshot({path:path.join(shots,'03-collapsed.png')});await page.locator('[name=design_mode][value=detailed]').check();check('다시 펼쳐도 항목 ID·입력 보존',await page.locator('[data-var]').getAttribute('data-var')===variableID&&await page.locator('[data-field=purpose]').inputValue()==='관측 조건 비교');
 await page.locator('[data-add-var=item]').click();await page.locator('[data-v-name]').last().fill('대상');await page.locator('[data-var]').last().locator('[data-move$=":-1"]').click();check('이동 후 안정 ID 유지',await page.locator('[data-var="'+variableID+'"]').count()===1);
 await page.locator('#design-approach').selectOption('EXISTING');check('관측 자료의 통제 표현',await page.locator('[data-var="'+variableID+'"] [data-v-role]').locator('option:checked').innerText()==='자료를 비교할 때 맞춰야 할 조건');
 const firstCard=page.locator('[data-var="'+variableID+'"]');await firstCard.locator('.design-card-details>summary').click();await firstCard.locator('[data-v-source]').selectOption(attachmentID);await firstCard.locator('[data-v-column]').fill('x');await firstCard.locator('[data-bind]').click();await firstCard.locator('[data-bind-result]').filter({hasText:'자료와 열을 연결했습니다.'}).waitFor();check('실제 CSV 헤더와 해시로 연결',await page.evaluate(id=>document.querySelector('#research-form').readDetailedDesign().variables.find(v=>v.id===id).binding?.column==='x',variableID));
 await page.screenshot({path:path.join(shots,'04-observational.png')});
 await page.evaluate(()=>document.querySelector('#research-form').flushDraft());await page.evaluate(()=>app.researchDraftSave);await page.reload();await page.locator('#list-new').waitFor();await page.locator('#list-new').click();await page.locator('#research-input-mode').waitFor();check('새로고침 후 같은 초안과 ID 복구',await page.locator('[data-var="'+variableID+'"]').count()===1&&await page.locator('[name=title]').inputValue()==='상세 입력 검사');
 check('첨부와 열 연결도 새로고침 후 보존',await page.evaluate(id=>document.querySelector('#research-form').readDetailedDesign().variables.find(v=>v.id===id).binding?.attachment_id===app.researchAttachments[0].attachment_id,variableID));
 await page.locator('[name=question]').fill('연구 목적: 원문 목적\n연구 대상: 관측 기록');
 await page.locator('#design-organize').click();await page.locator('[data-proposal-state]').waitFor();
 check('제안이 직접 입력을 자동 덮어쓰지 않음',await page.locator('[data-field=purpose]').inputValue()==='관측 조건 비교');
 await page.locator('[data-field=purpose]').fill('사용자가 다시 작성');await page.locator('#design-apply-proposals').click();check('변경 뒤 오래된 제안 적용 차단',await page.locator('#design-feedback').innerText().then(s=>s.includes('입력이 바뀌')));
 await page.locator('#design-organize').click();await page.locator('[data-proposal-index="1"]').check();await page.locator('#design-apply-proposals').click();check('선택 제안만 수용하고 직접 목적 유지',await page.locator('[data-field=subject]').inputValue()==='관측 기록'&&await page.locator('[data-field=purpose]').inputValue()==='사용자가 다시 작성');
 await page.locator('[name=question]').fill('1981~2000년과 2001~2020년의 전 지구 연간 기온 편차 평균 비교');await page.locator('[data-section="2"]>summary').click();await page.locator('[data-field=period]').fill('1990~2000, 2001~2010');await page.locator('#design-review').click();await page.waitForFunction(()=>document.querySelector('#design-feedback').textContent.includes('기간이 다릅니다'));
 check('기간 충돌은 한 항목으로 안내',await page.locator('#design-feedback').innerText().then(s=>s.includes('기간이 다릅니다')));
 await page.locator('#design-feedback').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(shots,'05-clarification.png')});
 const width=process.env.HTRSA_DESIGN_ZOOM==='1'?640:390;if(process.env.HTRSA_DESIGN_ZOOM!=='1')await page.setViewportSize({width,height:900});
 check('좁은 화면 상세 카드 가로 넘침 없음',await page.locator('#editor').evaluate(n=>n.scrollWidth<=n.clientWidth+2)&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 check('버튼 클릭 높이 44px 이상',await page.locator('[name=design_mode][value=detailed]').evaluate(n=>n.closest('label').getBoundingClientRect().height>=44));
 await page.locator('[name=design_mode][value=simple]').focus();await page.keyboard.press('Space');check('Space로 일반 설정 선택하고 초점 유지',await page.locator('[name=design_mode][value=simple]').evaluate(n=>n===document.activeElement&&n.checked));
 await page.locator('[name=design_mode][value=detailed]').check();page.once('dialog',dialog=>dialog.dismiss());await page.locator('#design-clear').click();check('초기화 취소하면 데이터 유지',await page.locator('[data-field=purpose]').inputValue()==='사용자가 다시 작성');
 page.once('dialog',dialog=>dialog.accept());await page.locator('#design-clear').click();check('초기화는 상세 조건만 제거',await page.locator('[data-var]').count()===0&&await page.locator('[name=title]').inputValue()==='상세 입력 검사');
 check('초기화 뒤에도 첨부 보존',await page.locator('#attachment-list').innerText().then(s=>s.includes('측정.csv')));
 await page.locator('[data-field=purpose]').fill('마지막으로 입력한 조건');await page.locator('[name=design_mode][value=detailed]').check();await page.locator('#research-next').click();await page.locator('#research-next').click();
 let submitted;await page.route('**/api/control/research/preflight',async route=>{submitted=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ready:false,first_blocker:'QA_LIVE_CALL_BLOCKED',reasons:['QA_LIVE_CALL_BLOCKED']})});});
 await page.locator('#research-start').click();await page.waitForFunction(()=>document.querySelector('#research-preflight').textContent.includes('QA_LIVE_CALL_BLOCKED'));
 check('시작 버튼은 마지막 입력과 첨부를 같은 스냅샷에 포함',submitted.detailed_design.fields.purpose.value==='마지막으로 입력한 조건'&&submitted.attachments.includes(attachmentID));await page.unroute('**/api/control/research/preflight');
 await page.locator('#research-prev').click();await page.locator('#research-prev').click();await page.locator('[name=design_mode][value=detailed]').check();
 await page.locator('#design-help').click();await page.locator('#guide-article h3').waitFor();check('기존 사용 안내에 상세 설계 장 연결',await page.locator('#guide-article').innerText().then(s=>s.includes('맞춤 연구 설계')&&s.includes('모름')&&s.includes('자료 연결')));
 await page.locator('#inspector-close').click();await page.locator('#editor-close').click();const info=JSON.parse(fs.readFileSync(path.join(folder,'execution.json'),'utf8'));
 await page.evaluate(async rid=>{app.view='research';app.rid=rid;app.tab='flow';await render();},info.research_id);await page.locator('.research-design-summary').waitFor();
 check('실제 분석 결과에 의도·사용·한계 요약',await page.locator('.research-design-summary').innerText().then(s=>s.includes('처음 정한 조건')&&s.includes('실제로 사용한 자료')&&s.includes('확인하지 못한')));
 await page.locator('.research-design-summary').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(shots,'06-result.png')});check('조건 수정 동작 접근 가능',await page.locator('#design-amend').isVisible());
 check("결과 요약도 좁은 화면에서 가로 넘침 없음",await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 await page.evaluate(async()=>{app.tab='report';await render();});await page.locator('.research-design-summary').waitFor();check('보고서 탭의 조건 요약은 한 번만 표시',await page.locator('.research-design-summary').count()===1);
 const after=await page.evaluate(()=>api('/qa/state'));check('편집·제안·조회에서 추가 연구·Agent·원장·유료 검사 생성 없음',before.researches===after.researches&&before.agents===after.agents&&after.requests===0&&after.checks===0);
 check('브라우저 오류·외부 요청 없음',errors.length===0);
 const result={passed:true,checks,errors,paid_calls:0,execution:'REAL_CHROME_OFFLINE_REAL_TOOLS_FAKE_AGENT',folder:path.relative(root,folder),screenshots:path.relative(root,shots),zoom:process.env.HTRSA_DESIGN_ZOOM==='1'?200:100};save(result);console.log(JSON.stringify({passed:true,checks:checks.length,paid_calls:0,folder:result.folder}));
}
main().catch(e=>{save({passed:false,checks,errors,error:e.message});console.error(e.stack);process.exitCode=1;}).finally(async()=>{if(context)await context.close();child?.kill();});
