// 실제 Chrome에서 연구 입력 방식과 화면 밖 안내를 검사한다. 유료 실행은 차단한다.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process'),{chromium}=require('./browser_runtime.cjs');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'build/tutorial-refresh/browser',crypto.randomUUID()),shots=path.join(root,'output/playwright/tutorial-refresh',path.basename(folder));
const checks=[],errors=[];let child,context,page;
function check(name,passed){checks.push({name,passed:!!passed});if(!passed)throw Error(name);}
function save(value){const text=JSON.stringify(value,null,2)+'\n';if(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(text))throw Error('UTF-8 검사 실패');fs.writeFileSync(path.join(folder,'result.json'),Buffer.from(text,'utf8'));}
async function main(){
 fs.mkdirSync(folder,{recursive:true});fs.mkdirSync(shots,{recursive:true});const env={...process.env};for(const k of Object.keys(env))if(k.endsWith('API_KEY'))delete env[k];
 child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-B','-X','utf8','qa/research_design_browser_fixture.py',folder],{cwd:root,env,windowsHide:true,stdio:['ignore','pipe','pipe']});
 let stderr='';child.stderr.on('data',v=>stderr+=v);
 const url=await new Promise((resolve,reject)=>{let out='';child.stdout.on('data',v=>{out+=v;const match=out.match(/http:\/\/127\.0\.0\.1:\d+\/#bootstrap=[A-Za-z0-9_-]{43}/);if(match)resolve(match[0]);});child.on('exit',()=>reject(Error(stderr.slice(-1600))));setTimeout(()=>reject(Error('검사 서버 준비 시간 초과')),30000).unref();});
 const profile=path.join(folder,'chrome-profile');fs.mkdirSync(path.join(profile,'Default'),{recursive:true});
 const zoom=process.env.PROBE_TUTORIAL_MODE_ZOOM==='1';const prefs=JSON.stringify({partition:{default_zoom_level:{x:zoom?Math.log(2)/Math.log(1.2):0}}});Buffer.from(prefs,'utf8').toString('utf8');fs.writeFileSync(path.join(profile,'Default/Preferences'),prefs);
 context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:false,viewport:{width:1280,height:900}});page=await context.newPage();page.setDefaultTimeout(15000);const origin=new URL(url).origin;
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin+'/')&&!r.url().startsWith('blob:'))errors.push('외부 요청');});
 const target=async selector=>page.waitForFunction(s=>document.querySelector('#tutorial-coach')?.dataset.target===s,selector);
 const visibleArrow=async()=>page.waitForFunction(()=>document.querySelector('#tutorial-coach')?.dataset.scrollDirection===''&&!document.querySelector('#tutorial-coach svg').hidden);
 const within=async()=>page.locator('.tutorial-coach-box').evaluate(n=>{const r=n.getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;});
 await page.goto(url);await page.locator('#list-new').waitFor();const before=await page.evaluate(()=>api('/qa/state'));
 if(zoom)check('Chrome 자체 200% 확대',await page.evaluate(()=>devicePixelRatio===2&&innerWidth===640));
 await page.locator('#list-new').click();await page.locator('#research-input-mode').waitFor();
 check('일반 설정 기본값과 선택지 위치',await page.locator('[name=design_mode][value=simple]').isChecked()&&await page.evaluate(()=>$('#research-input-mode').getBoundingClientRect().top<$('.research-page[data-page="0"]>h3').getBoundingClientRect().top));
 check('옛 자세히 만들기 버튼은 연구 화면에 표시하지 않음',!await page.locator('#design-toggle').isVisible()&&!await page.locator('#research-form').innerText().then(t=>t.includes('자세히 만들기')));
 check('설명 없는 화면에서도 실제 필수 항목 표시',await page.locator('#research-form .field-explanation,#research-form .muted,#research-form .verification-option small').count()===0&&await page.locator('[name=question]').locator('..').locator('.required-mark').count()===1&&await page.locator('[name=title]').locator('..').locator('.required-mark').count()===0);
 await page.locator('[name=title]').fill('방식 전환 검사');await page.locator('[name=question]').fill('온도와 성장량의 관계를 알아보고 싶다');
 await page.locator('[name=attachment_files]').setInputFiles({name:'참고.txt',mimeType:'text/plain',buffer:Buffer.from('연구에 필요한 참고 자료','utf8')});await page.waitForFunction(()=>app.researchAttachments?.length>0);
 await page.locator('#research-tutorial').click();await target('#research-input-mode');
 check('튜토리얼에서 입력 방식 먼저 질문',await page.locator('#tutorial-coach-text').innerText().then(t=>t.includes('일반 설정')&&t.includes('맞춤 연구 설계')));
 await page.locator('.tutorial-menu>summary').click();check('메뉴 펼침',await page.locator('.tutorial-menu').getAttribute('open')!==null);
 await page.locator('#tutorial-coach-count').click();check('안내 상자의 다른 곳을 누르면 메뉴 닫힘',await page.locator('.tutorial-menu').getAttribute('open')===null);
 await page.locator('[name=design_mode][value=detailed]').check();await page.waitForFunction(()=>$('#tutorial-coach')?.dataset.route==='research_design');
 check('선택한 방식으로 맞춤 튜토리얼 전환',await page.locator('#tutorial-coach-title').innerText()==='맞춤 연구 설계');
 check('주제·질문·자료도 맞춤 양식으로 교체',await page.locator('#design-overview [name=title]').count()===1&&await page.locator('#design-overview [name=question]').count()===1&&await page.locator('#design-materials [name=attachment_files]').count()===1&&await page.locator('[name=question]').count()===1);
 await page.locator('#tutorial-coach-next').click();await target('#research-form [name=title]');
 await page.locator('#tutorial-coach-next').click();await target('#research-form [name=question]');
 await page.locator('#tutorial-coach-next').click();await target('#research-form [name=attachment_files]');
 check('파일 안내에서 CSV 강제 인상 제거',await page.locator('#tutorial-coach-text').innerText().then(t=>t.includes('필요한 파일')&&!t.includes('CSV')&&t.includes('없어도')));
 await page.locator('#tutorial-coach-next').click();await target('#design-approach');check('맞춤 설계의 실제 입력 위치 안내',await page.locator('#tutorial-coach').getAttribute('data-route')==='research_design');
 await page.locator('#tutorial-coach-close').click();await page.locator('[data-field=purpose]').fill('식물이 잘 자라는 온도 알아보기');
 await page.locator('[name=design_mode][value=simple]').check();await page.locator('[name=design_mode][value=detailed]').check();
 check('방식 전환 후 질문·설계·첨부 보존',await page.locator('[name=question]').inputValue()==='온도와 성장량의 관계를 알아보고 싶다'&&await page.locator('[data-field=purpose]').inputValue()==='식물이 잘 자라는 온도 알아보기'&&await page.locator('#attachment-list').innerText().then(t=>t.includes('참고.txt')));
 await page.evaluate(()=>$('#research-form').flushDraft());await page.evaluate(()=>app.researchDraftSave);await page.reload();await page.locator('#list-new').waitFor();await page.locator('#list-new').click();await page.locator('#research-input-mode').waitFor();
 check('새로고침 후 방식·상세 조건·첨부 복구',await page.locator('[name=design_mode][value=detailed]').isChecked()&&await page.locator('[data-field=purpose]').inputValue()==='식물이 잘 자라는 온도 알아보기'&&await page.locator('#attachment-list').innerText().then(t=>t.includes('참고.txt')));
 if(!zoom)await page.setViewportSize({width:390,height:900});
 check('좁은 화면에서 양식 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)&&await page.locator('#editor').evaluate(n=>n.scrollWidth<=n.clientWidth+2));
 await page.screenshot({path:path.join(shots,'01-design.png')});
 await page.locator('#research-next').click();await page.locator('#research-tutorial').click();await page.locator('#tutorial-coach').waitFor();
 await page.locator('[name=public_search_query]').scrollIntoViewIfNeeded();await page.locator('[name=public_search_query]').focus();await target('#research-form [name=public_search_query]');
 check('검색어 예시와 외부 전송 주의 안내',await page.locator('#tutorial-coach-detail').innerText().then(t=>t.includes('plant growth temperature')&&t.includes('비공개')&&t.includes('비워')));
 check('예산에 미화 달러 표시',await page.locator('[name=run_limit_usd]').locator('..').innerText().then(t=>t.includes('USD(미화 달러)')));
 await page.evaluate(()=>{const field=$('#research-next');field.focus({preventScroll:true});$('#editor').scrollTop=0;});await target('#research-next');
 await page.waitForFunction(()=>$('#tutorial-coach')?.dataset.scrollDirection==='아래');
 check('화면 밖 아래 항목은 꺾인 화살표 대신 스크롤 안내',await page.locator('#tutorial-scroll-hint').innerText().then(t=>t.includes('아래'))&&await page.locator('#tutorial-coach svg').evaluate(n=>n.hidden)&&await page.locator('.tutorial-coach-arrow').getAttribute('d')===null);
 await page.locator('#research-next').scrollIntoViewIfNeeded();await visibleArrow();
 check('마지막 모델 안내 상자 화면 안 유지',await within());
 check('보이는 항목의 화살표는 직선',await page.locator('.tutorial-coach-arrow').getAttribute('d').then(d=>d.includes(' L ')&&!d.includes(' Q ')));
 await page.screenshot({path:path.join(shots,'02-next.png')});
 await page.evaluate(()=>{$('#editor').scrollTop=$('#editor').scrollHeight;document.querySelector('.model-option[data-active=true] input').focus({preventScroll:true});});await target('.model-option[data-active=true]');await page.waitForFunction(()=>$('#tutorial-coach')?.dataset.scrollDirection==='위');
 check('화면 밖 위 항목은 위로 스크롤 안내',await page.locator('#tutorial-scroll-hint').innerText().then(t=>t.includes('위로')));
 await page.locator('#research-next').click();await page.locator('#research-advanced>summary').click();await page.evaluate(()=>$('#research-start').scrollIntoView({block:'center'}));
 await target('#research-advanced>summary');await page.locator('#research-advanced>summary').scrollIntoViewIfNeeded();
 await page.locator('#tutorial-coach-next').click();await target('#research-advanced>summary');
 check('고급 설정이 접혀 있으면 숨은 전송 입력 대신 펼치기 위치 안내',await page.locator('[name=egress]').isVisible()===false&&await page.locator('#tutorial-coach-text').innerText().then(t=>t.includes('펼치')));
 await visibleArrow();check('접힌 고급 설정에서도 상자 위치·직선 화살표 정상',await within()&&await page.locator('.tutorial-coach-arrow').getAttribute('d').then(d=>d.includes(' L ')));
 await page.screenshot({path:path.join(shots,'03-collapsed.png')});
 await page.locator('.tutorial-menu>summary').click();await page.mouse.click(5,5);check('안내 밖의 실제 화면을 눌러도 메뉴 닫힘',await page.locator('.tutorial-menu').getAttribute('open')===null);
 await page.locator('#tutorial-coach-close').click();await page.locator('#research-prev').click();await page.locator('#research-prev').click();
 await page.locator('[name=design_mode][value=simple]').focus();await page.keyboard.press('Space');check('키보드로 설정 방식 선택',await page.locator('[name=design_mode][value=simple]').isChecked());
 const after=await page.evaluate(()=>api('/qa/state'));check('안내·방식 전환에서 연구·유료 요청·연결 검사·원장 변화 없음',before.researches===after.researches&&before.agents===after.agents&&before.requests===after.requests&&after.checks===0);
 check('브라우저 오류와 외부 요청 없음',errors.length===0);
 save({passed:true,checks,errors,paid_calls:0,zoom:zoom?200:100,execution:'REAL_CHROME_OFFLINE',folder:path.relative(root,folder),screenshots:path.relative(root,shots)});console.log(JSON.stringify({passed:true,checks:checks.length,zoom:zoom?200:100,folder:path.relative(root,folder)}));
}
main().catch(async e=>{const diagnostic=page?await page.evaluate(()=>({notice:$('#notice')?.textContent,page:$('#research-form')?.dataset.page,mode:$('#research-input-mode')?.outerHTML,design:typeof ProbeResearchDesign,body:$('#editor-content')?.innerText.slice(0,1000)})).catch(()=>null):null;if(page)await page.screenshot({path:path.join(shots,'failure.png')}).catch(()=>{});save({passed:false,checks,errors,error:e.message,diagnostic});console.error(e.stack);process.exitCode=1;}).finally(async()=>{if(context)await context.close();child?.kill();});
