// 실제 Chrome에서 선택·업로드·저장·모의 전송까지 확인한다.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');
const {chromium}=require('./browser_runtime.cjs');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'build/ui_start_unblock/browser',crypto.randomUUID());
const out=path.join(root,'output/playwright/ui_start_unblock');
fs.mkdirSync(folder,{recursive:true});fs.mkdirSync(out,{recursive:true});
const checks=[],shots=[],errors=[],egress=[];let browser,child;
function save(file,value){const text=JSON.stringify(value,null,2)+'\n';if(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(text))throw Error('UTF-8');fs.writeFileSync(file,Buffer.from(text,'utf8'));}
function check(name,value){checks.push({name,passed:Boolean(value)});save(path.join(folder,'progress.json'),{checks,errors});if(!value)throw Error('검사 실패: '+name);}
async function main(){
 const env={...process.env};for(const key of Object.keys(env))if(key.endsWith('API_KEY'))delete env[key];
 child=spawn(path.join(root,'.venv/Scripts/python.exe'),['-X','utf8','qa/ui_unblock_browser_fixture.py',folder],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env});
 let stderr='';child.stderr.on('data',v=>stderr+=v);
 const url=await new Promise((resolve,reject)=>{let output='';child.stdout.on('data',v=>{output+=v;const m=output.match(/http:\/\/127\.0\.0\.1:\d+\/#bootstrap=[A-Za-z0-9_-]{43}/);if(m)resolve(m[0]);});child.on('exit',()=>reject(Error('서버 종료: '+stderr.slice(-1000))));setTimeout(()=>reject(Error('서버 시작 시간 초과')),15000).unref();});
 const origin=new URL(url).origin;
 browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:720}});page.setDefaultTimeout(15000);
 page.on('pageerror',x=>errors.push(x.message));page.on('request',x=>{if(!x.url().startsWith(origin+'/'))egress.push(new URL(x.url()).origin);});
 await page.goto(url);await page.locator('#research-table').waitFor();
 check('자동 인증 후 티켓 제거',!page.url().includes('bootstrap'));
 await page.locator('#tutorial-skip').click();await page.locator('#tutorial-card').waitFor({state:'detached'});
 await page.locator('#list-new').click();if(await page.locator('#dismiss-explanations').count()){await page.locator('#dismiss-explanations').check();await page.locator('#without-explanations').click();}await page.locator('#research-form').waitFor();
 async function capture(name){const target=path.join(out,name+'.png');await page.screenshot({path:target});shots.push(path.relative(root,target).replaceAll('\\','/'));check(name+' 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}
 const model=id=>page.locator('input[name="catalog-model"][value="'+id+'"]');
 const select=async id=>{if(!await model(id).isVisible())await page.locator('#more-models').click();await model(id).check();};
 check('첫 장 고급 설정 숨김',!await page.locator('#research-advanced').isVisible());
 check('선택 파일 없음',await page.locator('#attachment-list .attachment-row').count()===0);
 check('문헌 기본 참',await page.locator('[name="search_required"]').isChecked());
 check('새 검색 상한 기본 10',await page.locator('[name="search_attempt_limit"]').inputValue()==='10');
 check('파일 확장자 제한 없음',await page.locator('[name="attachment_files"]').getAttribute('accept')===null);
 check('여러 파일 선택',await page.locator('[name="attachment_files"]').getAttribute('multiple')!==null);
 check('형식 선택 없음',await page.locator('[name="report_style"],[name="report_format"]').count()===0);
 check('등록 버튼 없음',await page.getByRole('button',{name:'선택한 모델 등록',exact:true}).count()===0);
 check('전송 없는 초기 화면',!fs.existsSync(path.join(folder,'observed.json')));
 await capture('01-defaults-desktop');
 await page.locator('[name="question"]').fill('자료 없이 관계를 검토해 주세요.');await page.locator('#research-next').click();
 await page.locator('#more-models').click();
 check('더보기 마지막',await page.locator('#research-model-picker').evaluate(e=>e.lastElementChild.id==='more-models'));
 check('확장 시 추천 묶음 사라짐',await page.locator('#featured-models').count()===0);
 await select('m');await select('m2');
 check('v4 확장 시 제공사 그룹으로 복귀',await page.locator('#selected-models input').count()===0&&await page.locator('.provider-group input[value="m"]:checked,.provider-group input[value="m2"]:checked').count()===2);
 check('중복 선택 행 없음',await model('m').count()===1&&await model('m2').count()===1);
 check('상속 모델 이름 실제 표시',(await page.locator('[name="manager"] option').first().textContent()).includes('검사 모델 m'));
 await model('m').evaluate(e=>e.scrollIntoView({block:'start'}));
 await capture('02-model-picker');
 const unregistered=await page.locator('[name="catalog-model"]').evaluateAll(es=>es.find(e=>e.value.startsWith('openai|'))?.value);
 check('실제 목록 미등록 모델 존재',Boolean(unregistered));
 await page.locator('input[name="catalog-model"]').evaluateAll((es,key)=>es.find(e=>e.value===key).click(),unregistered);
 await page.waitForFunction(()=>JSON.parse(document.querySelector('#research-form').dataset.modelPool||'[]').some(x=>x.startsWith('AUTO-')));
 check('선택만으로 안정된 자동 구성 생성',await page.evaluate(async()=>{const s=await(await fetch('/api/control/settings')).json();return s.models.some(x=>x.profile_id.startsWith('AUTO-')&&x.connection_id==='catalog'&&x.price===null&&x.capability_status==='unknown');}));
 await page.locator('input[name="catalog-model"]').evaluateAll((es,key)=>es.find(e=>e.value===key).click(),unregistered);
 check('모델 선택이 API를 호출하지 않음',!fs.existsSync(path.join(folder,'observed.json')));
 await page.locator('#more-models').click();check('접은 뒤 선택 유지',await page.locator('#selected-models input:checked').count()===2);
 await page.locator('#performance').focus();await page.keyboard.press('ArrowRight');
 check('슬라이더 키보드',await page.locator('#performance-detail').textContent()==='high');
 check('슬라이더 접근성 현재 값',await page.locator('#performance').getAttribute('aria-valuetext')==='high');
 check('모든 단계 라벨 없음',await page.locator('.performance-labels').count()===0);
 check('슬라이더 조작 높이',await page.locator('#performance').evaluate(e=>e.getBoundingClientRect().height>=44));
 await page.locator('#research-next').click();
 await page.locator('[name="advanced_performance_profile"]').selectOption('MAX');
 await page.locator('#research-prev').click();await page.locator('#performance').fill('1');await page.locator('#research-next').click();
 check('고급 상속 우선 부담 표시',await page.locator('#performance-badge').innerText()==='높음');
 check('고급 적용 표시',await page.locator('#preset-customized').textContent()==='고급 설정 적용 중');
 await page.locator('[name="manual_role_override"]').check();
 check('고급 실제 모델 선택지',await page.locator('[name="analysis_planner_worker"] option[value="m2"]').count()===1);
 await capture('03-advanced');
 await page.locator('#reset-recommended').click();
 check('고급 초기화 상속 복원',await page.locator('[name="advanced_performance_profile"]').inputValue()===''&&await page.locator('#performance-badge').innerText()==='중간');
 await page.locator('#research-prev').click();await page.locator('#research-prev').click();
 const files=[
  {name:'같은이름.txt',mimeType:'text/plain',buffer:Buffer.from('한글 자료','utf8')},
  {name:'보관.zip',mimeType:'application/zip',buffer:Buffer.from('PK-opaque')},
  {name:'설정.json',mimeType:'application/json',buffer:Buffer.from('{"items":[1]}')},
 ];
 await page.locator('[name="attachment_files"]').setInputFiles(files);
 await page.waitForFunction(()=>document.querySelectorAll('#attachment-list .attachment-row').length===3&&!document.querySelector('#attachment-list').textContent.includes('업로드'));
 check('여러 형식 상태', (await page.locator('#attachment-list').innerText()).includes('직접 분석 미지원')&&(await page.locator('#attachment-list').innerText()).includes('내용 읽기 완료'));
 await page.locator('[name="attachment_files"]').setInputFiles([files[0]]);
 await page.waitForFunction(()=>document.querySelectorAll('#attachment-list .attachment-row').length===4&&!document.querySelector('#attachment-list').textContent.includes('업로드'));
 check('같은 이름 추가 배치',await page.locator('#attachment-list .attachment-row').count()===4);
 await capture('04-attachments');
 while(await page.locator('#attachment-list [data-delete-upload]').count())await page.locator('#attachment-list [data-delete-upload]').first().click();
 await page.waitForTimeout(500);
 check('삭제 서버 원본 제거',await page.evaluate(async()=>{const id=document.querySelector('#research-form').dataset.draftId;return (await(await fetch('/api/control/attachments?draft_id='+id)).json()).length===0;}));
 check('삭제한 업로드 실제 서버 파일 0',fs.readdirSync(path.join(folder,'workspace/attachments')).length===0);
 await page.locator('#research-next').click();await page.setViewportSize({width:390,height:844});await page.locator('#performance').evaluate(e=>e.scrollIntoView({block:'center'}));await capture('05-narrow');
 await page.setViewportSize({width:1280,height:720});await page.evaluate(()=>document.documentElement.style.zoom='2');await page.locator('#performance').evaluate(e=>e.scrollIntoView({block:'center'}));await capture('06-zoom-200');await page.evaluate(()=>document.documentElement.style.zoom='');
 await model('m').click();
 await page.locator('#research-next').click();await page.locator('#research-smoke').click();
 await page.waitForFunction(()=>document.querySelector('#notice[data-status=success]')?.textContent.includes('AI 응답을 확인했습니다.'));
 const smoke=JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8'));
 check('질문·파일 없이 실제 모의 연결 전송 1회',smoke.length===1&&smoke[0].model==='manual-m2'&&!smoke[0].structured);
 check('연결 검사 연구 생성 없음',await page.evaluate(async()=> {const data=await(await fetch('/api/control/research')).json();return (Array.isArray(data)?data:data.items).length===0;}));
 await capture('07-smoke');
 if(await page.locator('#research-form').getAttribute('data-page')==='2')await page.locator('#research-prev').click();
 await page.locator('#more-models').click();await model('m').check();await model('m2').click();await page.locator('[name=search_policy]').selectOption('DISABLED');
 await page.locator('#research-next').click();await page.locator('#research-start').click();
 await page.locator('#research-form').waitFor({state:'hidden'});
 await page.locator('#run-content').waitFor();await capture('08-start-flow');
 const runs=await page.evaluate(async()=>{const data=await(await fetch('/api/control/research')).json();return Array.isArray(data)?data:data.items;});
 check('한 모델·자료 없음·고급 닫힘 실제 시작',runs.length===1);
 const rid=runs[0].research_id,control=await page.evaluate(async rid=>await(await fetch('/api/control/research/'+rid+'/control')).json(),rid);
 check('모든 역할 최신 선택 m 상속',Object.values(control.snapshot.routing).every(x=>x==='m'));
 check('웹 검색 해제와 파일 없음 저장',control.snapshot.search_required===false&&control.snapshot.search_policy==='DISABLED'&&control.snapshot.attachments.length===0&&control.snapshot.source===null);
 const calls=JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8'));
 check('Start 최신 선택 모의 관리자 요청',calls.length===3&&calls[1].model==='manual-m'&&calls[1].contract_request&&calls[2].model==='manual-m'&&calls[2].contract_request);
 check('허위 연구 결과 없이 자료 부족 종료',control.status==='INSUFFICIENT_DATA');
 const pdf=await page.evaluate(async rid=>{const r=await fetch('/api/control/research/'+rid+'/report.pdf');return {status:r.status,type:r.headers.get('content-type'),head:Array.from(new Uint8Array(await r.arrayBuffer()).slice(0,5))};},rid);
 check('실제 PDF 엔드포인트',pdf.status===200&&pdf.type==='application/pdf'&&JSON.stringify(pdf.head)===JSON.stringify([37,80,68,70,45]));
 check('CSRF 경계 유지',await page.evaluate(async()=> (await fetch('/api/control/research/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status===403));
 await page.reload();await page.locator('#run-content').waitFor();await page.locator('#tutorial-decline').click();await page.locator('#tutorial-card').waitFor({state:'detached'});check('새로고침 참여 선택에서도 유료 모의 요청 추가 없음',JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).length===3);check('새로고침 중복 전송 없음',JSON.parse(fs.readFileSync(path.join(folder,'observed.json'),'utf8')).length===3);
 await page.locator('[data-view="research"]').click();await page.locator('#list-new').click();await page.locator('#research-form').waitFor();
 check('완료한 초안 제출 키 재사용 안 함',await page.locator('[name="question"]').inputValue()==='');
 check('브라우저 오류 없음',errors.length===0);check('외부 요청 없음',egress.length===0);
 check('브라우저 저장소 비밀 없음',await page.evaluate(()=>localStorage.length===0&&sessionStorage.length===0));
 save(path.join(root,'build/ui_start_unblock/browser_results.json'),{execution:'OFFLINE_EXPLICIT_MOCK_TRANSPORT_REAL_CHROME',checks,shots,observed:calls,errors,external_requests:egress,folder:path.relative(root,folder).replaceAll('\\','/')});
 console.log(JSON.stringify({passed:checks.length,screenshots:shots.length,fake_provider_requests:calls.length,live:'NOT_VALIDATED'}));
}
main().catch(e=>{save(path.join(folder,'failure.json'),{error:e.message,checks,errors});console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();child?.kill();});
